meta_product_name: "Locify"
meta_title: "Locify - Make local shopping easy"
meta_description: "Marketplace for local products with same-day delivery"
meta_image: "cover.png" # should exist in `app/assets/images/`
